### ISSUE TITLE
Server crashes with playerNameUpdateRate

### ISSUE THREAD

**Issue by sndmax** [Patbox/StyledPlayerList#11]
If "playerNameUpdateRate" has different than "-1" - server crashes.

Loader: Fabric 1.19.2
Pack: Medieval MC 20.5 (MMC1)

Error:

> Description: Exception in server tick loop
java.lang.NoSuchMethodError: 'void net.minecraft.network.packet.s2c.play.PlayerListS2CPacket.<init>(net.minecraft.network.packet.s2c.play.PlayerListS2CPacket$Action, net.minecraft.server.network.ServerPlayerEntity)'
	at MC//net.minecraft.server.network.ServerPlayNetworkHandler.styledPlayerList$updateName(ServerPlayNetworkHandler.java:13108)
	at MC//net.minecraft.server.network.ServerPlayNetworkHandler.handler$hbm000$styledplayerlist$styledPlayerList$updatePlayerList(ServerPlayNetworkHandler.java:13066)
	at MC//net.minecraft.server.network.ServerPlayNetworkHandler.tick(ServerPlayNetworkHandler.java:334)
	at MC//net.minecraft.network.ClientConnection.tick(ClientConnection.java:248)
	at MC//net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo.java:183)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:886)
	at MC//net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer.java:289)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base@20.0.1/java.lang.Thread.run(Thread.java:1623)

Config:

> {
  "CONFIG_VERSION_DONT_TOUCH_THIS": 1,
  "_comment": "Before changing anything, see https://github.com/Patbox/StyledPlayerList#configuration",
  "defaultStyle": "default",
  "updateRate": 20,
  "displayOnSingleplayer": true,
  "switchMessage": "Your player list style has been changed to: <gold>${style}</gold>",
  "unknownStyleMessage": "<red>This style doesn't exist!</red>",
  "permissionMessage": "<red>You don't have required permissions!</red>",
  "changePlayerName": true,
  "playerNameFormat": "%player:displayname%     %playerex:level%",
  "updatePlayerNameEveryChatMessage": false,
  "playerNameUpdateRate": 20,
  "permissionNameFormat": []
}

**Comment by Patbox** [comment]
You are using wrong version for your MC version

**Comment by sndmax** [comment]
Thank you, didnt notice it was 1.19.3
